# Generated by Django 2.1.2 on 2018-10-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='livre_images', verbose_name='image'),
        ),
    ]
