# Generated by Django 2.1.2 on 2018-10-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_livre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='vendu',
            field=models.BooleanField(default=False),
        ),
    ]
