# Generated by Django 2.1.2 on 2018-11-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_auto_20181106_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='format',
            field=models.CharField(blank=True, choices=[('POCHE', 'Poche'), ('CARTONNE', 'Cartonné'), ('GRAND', 'Grand format')], max_length=15, null=True),
        ),
    ]
