# Generated by Django 2.1.2 on 2018-11-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0003_auto_20181106_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='livre',
            name='etats',
            field=models.ManyToManyField(related_name='etat_liste', to='livres.Etat'),
        ),
    ]
