# Generated by Django 2.1.2 on 2018-10-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0003_livre_vendu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
