# Generated by Django 2.1.2 on 2018-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0004_auto_20181120_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='etats',
            field=models.ManyToManyField(blank=True, null=True, related_name='etat_liste', to='livres.Etat'),
        ),
    ]
