# Generated by Django 2.1.2 on 2018-10-25 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livres', '0005_auto_20181024_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteurlivre',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='auteurlivre',
            name='livre',
        ),
        migrations.AddField(
            model_name='livre',
            name='auteurs',
            field=models.ManyToManyField(related_name='livre_liste', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AuteurLivre',
        ),
    ]
