# Generated by Django 2.1.2 on 2018-11-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0005_auto_20181120_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='photo',
        ),
        migrations.AlterField(
            model_name='livre',
            name='etats',
            field=models.ManyToManyField(blank=True, related_name='etat_liste', to='livres.Etat'),
        ),
    ]
