# Generated by Django 2.1.2 on 2018-10-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0006_auto_20181025_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='auteurs',
            field=models.ManyToManyField(related_name='livre_liste', to='livres.Auteur'),
        ),
    ]
